Test suites
partiql/partiql-lang-kotlin pull request #1246
Opened 2023-10-16 19:39 UTC by RCHowell

## Description
We wish to re-use all of the PartiQLSchemaInferencer tests as we continue to work on the resolved query plan. This PR separates test inputs from results for re-use in testing type, evluation, transpilation, planning etc.

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**
No, internal testing packages

- Any backward-incompatible changes? **[YES/NO]**
N/A

- Any new external dependencies? **[YES/NO]**
N/A

- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md)
  and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **[YES/NO]**

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-16 22:01 UTC, johnedquinn requested changes

2023-10-16 22:01 UTC, johnedquinn commented on partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
Is there a plan for removing tests in this file?

2023-10-17 16:46 UTC, RCHowell commented on partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
So long as PartiQLSchemaInferencer is part of the public API (which it totally should be!) then we should keep this.

2023-10-17 16:46 UTC, RCHowell commented on partiql-planner/src/test/kotlin/org/partiql/planner/PlannerTestCase.kt
> +package org.partiql.planner
ack

2023-10-19 17:26 UTC, johnedquinn approved these changes

2023-10-19 17:46 UTC, merged