Inferencer removal
partiql/partiql-lang-kotlin pull request #1302
Opened 2023-12-12 22:58 UTC by yliuuuu

## Relevant Issues
- [Closes/Related To] Issue N/A

## Description
- Remove Inferencer
- Ported the existing inferencer test case to Planner Project. 
- TODO: There are some duplicated tests needs to be cleaned up, this PR intensionally chooses to not address them to reduce the size of the diff. 

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**
  - Yes. 

- Any backward-incompatible changes? **[YES/NO]**
  -  Yes. A public API is removed. In order to use the same functionality, one would need to user the `Planner` API. 

- Any new external dependencies? **[YES/NO]**
  - No.

- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md)
  and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **[YES/NO]**
  - Yes.
  
## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-13 18:34 UTC, RCHowell requested changes

2023-12-13 18:34 UTC, RCHowell commented on CHANGELOG.md
> +- **Breaking** Removed `org.partiql.lang.planner.transforms.PartiQLSchemaInferencer`. In order to achieve the same functionality, one would need to use the `org.partiql.planner.PartiQLPlanner`.
Maybe add an example? For "same functionality" it's really just getting the query return type.

2023-12-14 17:35 UTC, johnedquinn reviewed
LGTM. Just echoing Robert's comment about an example.

2023-12-14 19:35 UTC, RCHowell approved these changes

2023-12-14 19:35 UTC, merged