Adds a CompilationErrorHandling flag to evaluator
partiql/partiql-lang-kotlin pull request #1416
Opened 2024-04-08 21:44 UTC by johnedquinn

## Relevant Issues
- [Closes/Related To] Issue #XXX

## Description
- Adds a CompilationErrorHandling flag to evaluator for the sake of handling all of the "handle always missing" errors. All of the conformance tests do NOt handle the "handle always missing" errors. Therefore, to be 1:1 with the EvaluatingCompiler, I've added a flag that a user can override to specify the compilation behavior for RexOpErr.

## Other Information
- Updated Unreleased Section in CHANGELOG: **NO**
- Any backward-incompatible changes? **NO**
- Any new external dependencies? **NO**
- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md)
  and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **YES**

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-18 18:30 UTC, johnedquinn commented on partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprError.kt
> +}
Updated the compiler accordingly

2024-04-18 21:44 UTC, johnedquinn commented on partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprError.kt
> +}
For some context, I initially added ExprError for both RexOpErr and RexOpMissing due to how it fixed failing conformance tests. But, now looking at the tests, I actually notice that those conformance tests are wrong. Specifically, in `undefined-variable-behavior.ion`, all of these tests failed when I didn't compile RexOpErr into an ExprError. That being said, PartiQL Spec Section 10 actually highlights why these tests are wrong. We are good to go ahead with this change, and I'll update those tests.

2024-04-18 23:43 UTC, RCHowell commented on partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprError.kt
> +}
What I am saying is that the Compiler.kt fails to compile any query that contains a Rex.Op.Err.

If an error is a "mis-typing" error, then the _planner_ inserts Rex.Op.Missing which the compiler may (or may not) recover from given the typing mode.

There should be no ExprError.kt

2024-04-18 23:44 UTC, RCHowell requested changes
Compiler should blow up on Rex.Op.Err

2024-04-22 15:17 UTC, RCHowell commented
Close in favor of https://github.com/partiql/partiql-lang-kotlin/pull/1437

2024-04-22 15:17 UTC, closed without merging