Eradicates premature failures when visiting error nodes
partiql/partiql-lang-kotlin pull request #1453
Opened 2024-05-02 17:23 UTC by johnedquinn

## Relevant Issues
- None

## DRAFT Description

I'll fill this out more soon.

According to the PartiQL Specification:
> For example, in the presence of schema validation, an PartiQL query processor can throw a compile-time error
> when given the path expression {a:1, b:2}.c. In a more important and common case, an PartiQL implementation can
> utilize the input data schema to prove that a path expression always returns MISSING and thus throw a
> compile-time error.

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**
  - < If NO, why? >

- Any backward-incompatible changes? **[YES/NO]**
  - < If YES, why? >
  - < For this purpose, we define backward-incompatible changes as changes that—when consumed—can potentially result in
errors for users that are using our public APIs or the entities that have `public` visibility in our code-base. >

- Any new external dependencies? **[YES/NO]**
  - < If YES, which ones and why? >
  - < In addition, please also mention any other alternatives you've considered and the reason they've been discarded >

- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md)
  and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **[YES/NO]**

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-05-07 15:16 UTC, RCHowell requested changes

2024-05-07 15:16 UTC, RCHowell commented on partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
> +            return rexOpErr("Unresolved cast: ${node.arg.type} to ${node.target}.", emptyList())
I don't think the public plan should have error nodes btw... I suggest PlanTransform use the antlr style error listeners. It's a bit silly to hide errors in a tree, then make the compiler later throw them.

We have _two_ error nodes at the moment, but should only have _one_.

We have,
 - rexOpError
 - rexOpMissing

The _rexOpError_ should NOT exist in the public plan IR, but _rexOpMissing_ should. The _rexOpMissing_ operation represents a typing error that either throws or becomes MISSING in the evaluator.

The _rexOpError_ is an outright error that will _never_ compile.

2024-05-09 18:14 UTC, johnedquinn commented
> > So, this translates to deferring failure until evaluation.
> 
> The specification says most commonly you want to error, but _can_ defer. This is what [Yingtao's PR for planner modes](https://github.com/partiql/partiql-lang-kotlin/pull/1385) handles. I urge that signal mode is the default.

The focus of this PR is to bridge the conformance gap (this PR passes an additional 20 tests). The existing conformance tests defer on erroring as does the existing evaluator. To accommodate your suggestion, there are two things I could do:
1. Update the tests to allow for erroring during compilation.
2. Or, add a flag to the engine (not default) to defer on erroring. Then, in the conformance tests runs, I can use the non-default flag to match the functionality of the existing evaluator.

2024-05-14 19:22 UTC, RCHowell commented
I still don't quite understand the purpose here other than conformance tests being wrong. I believe Yingtao's planner work and the compiler implementation are correct.

**HOWEVER**

I think perhaps we should be making changes in the _planner_ not the compiler.

**Here are the Options afaik** 

1. If we can confirm that the tests are **correct**, then the fix should go into the planner.
2. If the tests are **incorrect**, then we can close this and open an issue in partiql-tests

2024-07-15 17:45 UTC, closed without merging