Updates CLI/Shell to use the V1 engine
partiql/partiql-lang-kotlin pull request #1458
Opened 2024-05-07 23:14 UTC by RCHowell

## Description

This PR updates the shell to use the V1 engine along with accepting input from stdin. Follow ups will include bridging backwards compatibility gaps with functions like read_file.

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**
No

- Any backward-incompatible changes? **[YES/NO]**
Yes

- Any new external dependencies? **[YES/NO]**
No

- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md)
  and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **[YES/NO]**
Yes

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-05-09 17:49 UTC, johnedquinn requested changes

2024-05-09 17:49 UTC, johnedquinn commented on partiql-cli/src/main/kotlin/org/partiql/cli/Main.kt
> +    lateinit var format: Pair<Format, Format>
This is unused.

2024-05-14 19:15 UTC, RCHowell commented on partiql-cli/README.adoc
> +cat sample.ion | partiql -i ion    # Load from stdin with the specified input format (-i) Ion.
Intentionally -i from psql

2024-05-14 19:15 UTC, RCHowell commented on partiql-cli/src/main/kotlin/org/partiql/cli/Main.kt
> +    lateinit var format: Pair<Format, Format>
For now

2024-07-29 18:47 UTC, johnedquinn approved these changes

2024-07-29 19:43 UTC, merged