Replaces ConnectorMetadata/BindingPath with the catalog interfaces.
partiql/partiql-lang-kotlin pull request #1536
Opened 2024-08-05 22:07 UTC by RCHowell

## Relevant Issues

#1496 

## Description

This PR replaces ConnectorMetadata with BindingPath/BindingName to use the Catalog interfaces such as Catalog, Identifier, Name, and Table. This is an intermediate step to replace the metadata layer with the catalog interfaces. This PR HAS to update the plugins, and it replaces PartiQLValue in the bindings to use Datum.

Finally, it introduces an initial implementation of the IonDatum which fills the role of the original Ion-valued backed ExprValue.

## Other Information
- Updated Unreleased Section in CHANGELOG: **NO**
- Any backward-incompatible changes? **NO**
- Any new external dependencies? **NO**
- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md)
  and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **YES**

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-05 22:08 UTC, RCHowell commented
This is a draft because I am working on confirming any impact to the conformance tests which @johnedquinn has worked so hard one 😁

2024-08-15 18:37 UTC, johnedquinn requested changes

2024-08-15 18:37 UTC, johnedquinn commented on partiql-spi/src/main/kotlin/org/partiql/value/ion/IonDatum.kt
> +                    null -> PType.typeBool()
Just a heads up -- you'll need to rebase from your most recently merged PR.

2024-08-15 18:37 UTC, johnedquinn commented on partiql-spi/src/main/kotlin/org/partiql/value/ion/IonDatum.kt
> +            Datum.nullValue()
```suggestion
            Datum.missing()
```

2024-08-15 18:37 UTC, johnedquinn commented on partiql-spi/src/main/kotlin/org/partiql/value/ion/IonDatum.kt
> +        return Datum.nullValue()
```suggestion
        return Datum.missing()
```

2024-08-15 18:37 UTC, johnedquinn commented on plugins/partiql-memory/README.md
> +        type = PType.typeFloat32(),
```suggestion
        type = PType.real(),
```

2024-08-15 18:37 UTC, johnedquinn commented on plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/LocalCatalog.kt
> +        }
```suggestion
        if (path.notExists() || path.isDirectory()) {
            return null
        }
```
If I'm reading this correctly.

2024-08-15 18:37 UTC, johnedquinn commented on plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/LocalCatalog.kt
> +        if (path.notExists() || path.isDirectory()) {
```suggestion
        if (path.notExists() || !path.isDirectory()) {
```

2024-08-21 20:39 UTC, johnedquinn approved these changes

2024-08-21 20:53 UTC, merged