Fix try-catch for conformance tests expecting an error
partiql/partiql-lang-kotlin pull request #1542
Opened 2024-08-07 22:25 UTC by alancai98

checking conformance test runner results

## Relevant Issues
- [Closes/Related To] Issue #XXX

## Description
- < A detailed description >

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**
  - < If NO, why? >

- Any backward-incompatible changes? **[YES/NO]**
  - < If YES, why? >
  - < For this purpose, we define backward-incompatible changes as changes that—when consumed—can potentially result in
errors for users that are using our public APIs or the entities that have `public` visibility in our code-base. >

- Any new external dependencies? **[YES/NO]**
  - < If YES, which ones and why? >
  - < In addition, please also mention any other alternatives you've considered and the reason they've been discarded >

- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md)
  and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **[YES/NO]**

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-07 22:56 UTC, alancai98 commented
Some additional test failures due to this change -- https://github.com/partiql/partiql-lang-kotlin/actions/runs/10292632996.

Some of these errors are properly caught by the planner but not detected by the evaluator. Regarding the planner errors, we should probably throw on these cases -- https://github.com/partiql/partiql-lang-kotlin/issues/1543.

2024-08-08 22:38 UTC, johnedquinn requested changes
This PR makes me think, why are we even catching these exceptions? Using exceptions for business logic is generally advised against. IMO, this whole method can be simplified by creating the `statement`/`actual` variables in each assertion block. Then, we can use a try-catch just for the `Assertion.EvaluationFailure` where it's required.

Though, it would also be nice to have each variant of `TestCase` implement their own assertion logic.

2024-08-08 22:38 UTC, johnedquinn commented on test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/test/TestRunner.kt
> +                        throw TestRunnerException("Expected error to be thrown but none was thrown.\n${case.name}\nActual result: $ion")
This error message isn't the intention behind Assertion.EvaluationSuccess.

2024-08-09 00:03 UTC, alancai98 commented
> This PR makes me think, why are we even catching these exceptions? Using exceptions for business logic is generally advised against. IMO, this whole method can be simplified by creating the `statement`/`actual` variables in each assertion block. Then, we can use a try-catch just for the `Assertion.EvaluationFailure` where it's required.
> Though, it would also be nice to have each variant of `TestCase` implement their own assertion logic.

Yeah the current `TestRunner` is somewhat confusing. This PR was initially meant to unblock some testing as part of #1542, but I'll take another look at refactoring the current `TestRunner`.

2024-08-09 19:36 UTC, johnedquinn approved these changes
Discussed offline -- to unblock Alan's work on the bag ops, I'm approving this PR. A follow-up will ensue.

2024-08-09 19:36 UTC, merged