Rewrites PLUS and BITWISE_AND implementations using new modeling
partiql/partiql-lang-kotlin pull request #1647
Opened 2024-11-14 17:54 UTC by johnedquinn

## Relevant Issues
- #1646 

## Description
- Rewrites PLUS and BITWISE_AND
  - Slightly updates how function instances are chosen. See FnResolver. 
  - See `ArithmeticDiadicOperator`. It holds a table of pointers to functions given two argument types. The function is in charge of providing the closest function impl, but the engine is still in charge of coercions and final resolution.
- Dynamic calls now hold functions, not functions instances since they haven't been resolved yet.

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-11-15 19:00 UTC, RCHowell requested changes

2024-11-15 19:00 UTC, RCHowell commented on partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/TypePrecedence.kt
> +internal val TYPE_PRECEDENCE: Map<Kind, Int> = listOf(
Top-level interval vals are ok afaik (functions were the leaked apis), but wouldn't hurt to put in a TypePrecedence object as a static field, kotlin is doing that anyways so let's at least control it.

2024-11-18 23:52 UTC, johnedquinn commented on partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnCollAgg.kt
> +        name,
We have some logic checking the contents of the signature. Specifically, checking for `is_struct`.

2024-11-18 23:59 UTC, johnedquinn commented on partiql-planner/src/main/kotlin/org/partiql/planner/internal/CoercionFamily.kt
> + * TODO: [DYNAMIC] should likely be removed in the future. This is currently only kept to map function signatures.
Yeah, I talked to Josh about this last week -- how our variant is more similar to dynamic than say Spark's variant (which requires explicit casts). I'll leave this for now, but I think I'm inclined to agree.

2024-11-19 00:52 UTC, RCHowell commented on partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnCollAgg.kt
> +        name,
The IS_<TYPE> is out of spec and would be its own node anyways. Other than is_struct, is there a reason why instances would need names? 

I can see it being useful for introspection. I don't think it should be removed, but I don't think it should be user-provided.

2024-11-19 00:56 UTC, RCHowell approved these changes

2024-11-19 17:29 UTC, merged