Adds documentation regarding thread safety of `CompilerPipeline`
partiql/partiql-lang-kotlin pull request #334
Opened 2020-11-25 01:37 UTC by alancai98

Adds to the kdoc, detailing how the builder instance of `CompilerPipeline` is not thread safe.

Possible TODOs:
- Should we also document this for the `CompilerPipeline` interface (not just the builder instance)?
- Should we add annotations of non-thread safety?
- Should we also document that `EvaluatingCompiler` is not thread safe?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-11-25 19:11 UTC, dlurton requested changes
- Should we also document this for the CompilerPipeline interface (not just the builder instance)?
    - I would, yes.
- Should we add annotations of non-thread safety?
    - Of what annotations specifically do you speak of?  I am not aware of any that aren't part of another library and I'd rather avoid taking a dependency on a new library just for that.
- Should we also document that EvaluatingCompiler is not thread safe?
   - `EvaluatingCompiler` is `internal`, but you can add a quick note to it if you'd like.

2020-11-25 19:11 UTC, dlurton commented on lang/src/org/partiql/lang/CompilerPipeline.kt
> +     */
Add:

> If used in a multithreaded application, use one instance of [CompilerPipeline] per thread.

2020-11-25 21:17 UTC, alancai98 commented on lang/src/org/partiql/lang/CompilerPipeline.kt
> +     */
Added.

2020-11-25 21:21 UTC, alancai98 commented
New revision includes updated kdoc to `CompilerPipeline` builder and interface. Also adds a note about thread safety to `EvaluatingCompiler`.

Regarding
>Of what annotations specifically do you speak of? I am not aware of any that aren't part of another library and I'd rather avoid taking a dependency on a new library just for that.

None in particular. I wasn't sure if there was any standard annotation to denote a class was not thread safe.

2020-12-08 00:54 UTC, dlurton approved these changes

2020-12-15 21:17 UTC, merged