Migrate `AstRewriterBase` to PIG's `VisitorTransform`
partiql/partiql-lang-kotlin pull request #356
Opened 2021-01-11 19:59 UTC by alancai98

Migrates `AstRewriterBase` to PIG's `VisitorTransform`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-11 23:40 UTC, dlurton requested changes
Overall LGTM (as it should since each commit was a previously reviewed PR!) but I think we need to add a `CompilerPipeline.addPreprocessingStep` overload for `PartiqlAst`.

2021-01-13 22:14 UTC, dlurton submitted a review, later dismissed
Actually, if you want you can do that `addProcessingStep` overload in a PR and merge this one.  Approving now so you have that option.

2021-01-15 21:56 UTC, alancai98 commented
New commit
- moves `MetaStrippingRewriter` back to the `src` directory and adds a deprecation warning
- adds back `RewriterTestBase` and adds a deprecation warning
- deletes deprecation warnings from `ExprNodeExtensions`

I felt the `MetaStrippingRewriter` and `RewriterTestBase` additions/changes are needed (at least for now) to not break existing client code that may rely on those public APIs. Deprecation warnings were added to prevent further usage.

I deleted the deprecation warnings in `ExprNodeExtensions` because the functions are still in use by the `EvaluatingCompiler`. In the future when we deprecate `ExprNode`, we should deprecate the `ExprNodeExtensions` functions.

As for the `addProcessingStep` overload, I will make a separate PR to track that change since it may involve adding some additional deprecation warnings.

2021-01-21 20:04 UTC, dlurton approved these changes

2021-01-21 20:49 UTC, merged