Cli add partiql input
partiql/partiql-lang-kotlin pull request #617
Opened 2022-05-31 17:47 UTC by johnedquinn

## Description of Changes
- Adds the `--input-format` flag to the CLI
- Adds the ability to handle PartiQL data format for input (before was only Ion)
- Updates the `read_file` function to read in a single Ion value
   - Before, the `read_file` function used to loop through the values of an Ion file and place all values within a bag. This limits our ability to differentiate between different Ion values. See the next bullet-point for more information.
- Updates the `write_file` function to write the actual result.
  - Before, the `write_file` function used to loop through the values within a bag/list and print those values. This would not allow for printing expressions like literals.
- Updates the documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-01 00:36 UTC, alancai98 requested changes
Thanks for diving deep into some of the inconsistencies with the existing PartiQL CLI + REPL! I think it's headed in the right direction and will improve the usability of the CLI + REPL for newcomers.

Left some mostly minor comments related to the documentation. Also think there needs to be some tests with the `input-file` CLI option set to `PARTIQL`.

2022-06-01 00:36 UTC, alancai98 commented on docs/user/CLI.md
> +-if, --input-format <InputFormat>     input format, requires the query option -- [PARTIQL (default), ION]
Is the default PARTIQL or ION? The default in [main.kt](https://github.com/partiql/partiql-lang-kotlin/blob/f33050e6a7f09ad7b9318af19f9ea1c5084bae4d/cli/src/org/partiql/cli/main.kt#L105) is ION. If the defaults are PARTIQL, may need to update the above text (and the [--help text](https://github.com/partiql/partiql-lang-kotlin/blob/f33050e6a7f09ad7b9318af19f9ea1c5084bae4d/cli/src/org/partiql/cli/main.kt#L50-L68)) to include the --input-format option.

2022-06-01 00:36 UTC, alancai98 commented on cli/src/org/partiql/cli/Cli.kt
> +        val partiql =
nit: non-descriptive variable. Should reference that we're reading in the input environment.

2022-06-01 00:36 UTC, alancai98 commented on cli/test/org/partiql/cli/CliTest.kt
> +            InputFormat.ION,
Could have some tests with `InputFormat.PARTIQL`. Also I don't think you should hard-code the this argument to the `Cli` but rather pass it in as another argument to `makeCli`. You could set the default `inputFormat` for `makeCli` to `ION` depending on what the actual default is.

2022-06-01 00:36 UTC, alancai98 commented on cli/test/org/partiql/cli/CliTestUtility.kt
> +        InputFormat.ION,
For consistency with the other `Cli` constructor args, I'd not hardcode the `inputFormat` argument but would rather pass it as an argument to `makeCliAndGetResult`.

2022-06-01 01:44 UTC, johnedquinn commented
ACK. I'll check the comments out and address. Appreciate it!

2022-06-01 16:32 UTC, johnedquinn commented on cli/src/org/partiql/cli/functions/ReadFile.kt
> +                val message = "As of June 2022, PartiQL requires that Ion files contain only a single Ion value for " +
Thanks! Will do.

2022-06-01 16:34 UTC, johnedquinn commented on docs/user/CLI.md
> +[
ACK. Nice catch.

2022-06-01 21:37 UTC, lziq commented
I like the idea, but I think we still need to discuss it with everyone to see if others agree. Also, there are some backward compatibility problems we need to take care of, such as throwing error when reading Ion file with multiple Ion values.

2022-06-01 22:39 UTC, alancai98 commented on docs/user/CLI.md
> +-of, --output-format <OutputFormat>   output format, requires the query option [PARTIQL (default), PARTIQL_PRETTY, ION_TEXT, ION_BINARY]
Don't think this comment was addressed. Might also need addressed for [main.kt](https://github.com/partiql/partiql-lang-kotlin/blob/860f78023f0a2a1042d9797668c5da241b24163a/cli/src/org/partiql/cli/main.kt#L133-L135)

2022-06-01 22:52 UTC, alancai98 commented on docs/user/CLI.md
> +To view the AST of a PartiQL statement, type one and press enter only *once*, then type `!!` and press enter:
bump^

2022-06-01 22:52 UTC, alancai98 commented on docs/user/CLI.md
> +and they must contain only a single Ion value (typically a list).
bump^

2022-06-01 23:16 UTC, alancai98 requested changes
Some other minor comments related to documentation + tests. Otherwise looks good. Also there were some other comments that I don't believe were addressed (GitHub sometimes hides comments if there are too many of them and you have to hit "Load more").

![image](https://user-images.githubusercontent.com/23245405/171516889-64d480c7-c518-4912-a891-a18dfe4c067e.png)

Agree w/ @lziq that we need to decide as a team on the breaking semantic changes to the CLI + REPL. I think these changes make the CLI more usable.

2022-06-01 23:16 UTC, alancai98 commented on cli/src/org/partiql/cli/main.kt
> +private val inputFormatOpt = optParser.acceptsAll(listOf("input-format", "if"), "output format, requires the query option")
Might have missed this from the first review. Hint is incorrect

```suggestion
private val inputFormatOpt = optParser.acceptsAll(listOf("input-format", "if"), "input format, requires the query option")
```

2022-06-01 23:16 UTC, alancai98 commented on cli/test/org/partiql/cli/CliTest.kt
> +        val partiqlInputResult = makeCliAndGetResult(query, input, inputFormat = InputFormat.PARTIQL)
Thanks for adding some tests with the `InputFormat.PARTIQL`. I think we may need a couple additional tests:
- use `InputFormat.PARTIQL` to load an input that uses PartiQL syntax (e.g. a bag with the angle bracket syntax: `<<{'a': 1}>>`)
- use `InputFormat.ION` to load an input with PartiQL syntax (e.g. bag w/ angle brackets), which should error

AFAICT, the inputs for these tests just use Ion syntax and nothing specific to PartiQL.

2022-06-01 23:20 UTC, alancai98 commented
Btw to keep the commit history slightly cleaner for PRs as `main` is updated, I generally prefer rebasing `main` on to the working branch rather than merging. This can help prevent unrelated merge commits from appearing in the PR.

2022-06-02 16:47 UTC, johnedquinn commented
Yeah, I'm still getting used to the approval process and didn't realize there were hidden comments. Addressed. Thanks for pointing that out @alancai98

2022-06-02 18:28 UTC, johnedquinn commented
As discussed with team, going to add a flag to use the old implementation -- along with modifying the exception message specifying the flag use.

2022-06-02 21:21 UTC, alancai98 approved these changes
Thanks for addressing the feedback and adding in the `-w`/`--wrap-ion` flag to the CLI. Left some minor comments and a comment related to `read_file`. Feel free to decide if they're relevant.

2022-06-02 21:21 UTC, alancai98 commented on cli/src/org/partiql/cli/Cli.kt
> +            throw IllegalArgumentException("Specifying --wrap-ion requires that the input format be ${InputFormat.ION}.")
nit: "Specifying -w/--wrap-ion requires..."

2022-06-02 22:18 UTC, merged