Fixes add_to_global_env highlighting
partiql/partiql-lang-kotlin pull request #657
Opened 2022-06-29 18:15 UTC by RCHowell

[*Issue #, if available:*](https://github.com/partiql/partiql-lang-kotlin/issues/651)

*Description of changes:*

Fixed the `!add_to_global_env` highlighting. This will highlight the PartiQL value in the `!add_to_global_env` command using the lexer/parser. 

*Have you updated the `Unreleased` section of `CHANGELOG.md` with your changes? (y/n), If not, please explain why:*

No, small bug fix

*Does your PR include any backward-incompatible changes? (y/n), if yes, please explain the reason. In addition, please
 also mention any other alternatives you've considered and the reason they've been discarded?:*

No

```
For this purpose, we define backward-incompatible changes as changes that—when consumed—can potentially result in 
errors for users that are using our public APIs or the entities that have `public` visibility in our code-base.
```

*Does your PR introduce a new external dependency? (y/n), if yes, please explain the reason. In addition, please
also mention any other alternatives you've considered and the reason they've been discarded?:*

No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-29 18:16 UTC, RCHowell commented
https://user-images.githubusercontent.com/5731503/176507457-e1b38404-c3de-4a38-9552-a3600e3015b0.mov

2022-06-30 18:38 UTC, johnedquinn requested changes
Looks great. Decided to pull the changes for manual testing, and one thing is broken. Essentially pressing enter after `!add_to_global_env`. See my suggestions.

2022-06-30 18:38 UTC, johnedquinn commented on cli/src/org/partiql/shell/ShellHighlighter.kt
> +                AttributedString("")
```suggestion
                AttributedString(line)
```

2022-06-30 18:38 UTC, johnedquinn commented on cli/src/org/partiql/shell/ShellHighlighter.kt
> +                ADD_TO_GLOBAL_ENV_COMMAND
After pulling this locally, if you type in `!add_to_global_env` and press Return immediately, there's an out of bounds exception. Seems like it's from this line. We want to color the entire line and return. If we go back to when we first added highlighting (or before highlighting), we were allowed to do this. See the suggestion that looks like it fixes this:
```suggestion
                AttributedString(line, AttributedStyle.DEFAULT.foreground(AttributedStyle.CYAN))
```

2022-06-30 21:02 UTC, johnedquinn approved these changes
LGTM.

2022-06-30 21:05 UTC, merged