Split Optin annotation to feature level
partiql/partiql-lang-kotlin pull request #964
Opened 2023-01-10 18:42 UTC by yliuuuu

## Relevant Issues
- N/A

## Description
-  Deprecates the project level opt-in annotation `PartiQLExperimental` and split it into feature level. `ExperimentalPartiQLCompilerPipeline` and `ExperimentalWindowFunctions`.
- Add an `experimental()` function to initialize a compiler with the experimental features. (currently just the window operator). 
- Opt-in annotation at line level in example file. 

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**
  - Yes. 
- Any backward-incompatible changes? **[YES/NO]**
  - Yes. The old project level opt-in annotation is deprecated. 
  - < For this purpose, we define backward-incompatible changes as changes that—when consumed—can potentially result in
errors for users that are using our public APIs or the entities that have `public` visibility in our code-base. >
- Any new external dependencies? **[YES/NO]**
  - No. 
  - < In addition, please also mention any other alternatives you've considered and the reason they've been discarded >

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-17 19:32 UTC, vgapeyev requested changes
The @OptIn part is largely all right, but let's see how this looks without the `experimental()` method, as we discussed.

2023-01-17 19:32 UTC, vgapeyev commented on lang/src/main/kotlin/org/partiql/lang/compiler/PartiQLCompilerBuilder.kt
> +        fun experimental() = PartiQLCompilerBuilder().customOperatorFactories(EXPERIMENTAL_RELATIONAL_OPERATOR_FACTORIES)
As we discussed in-person, this method would be addressing some sort of a possible need of a PartQL-*language* customer who might be worried about running code containing features we consider experimental, even if the customer does not use these features. 

This need is different from what @OptIn is for, which is for communicating to a PartiQL-*library* customer that certain of our APIs are not final yet. 

So, let's go without `experimental()` for now.
Instead, WindowRelationalOperatorFactoryDefault should just be added to DEFAULT_RELATIONAL_OPERATOR_FACTORIES, and get the @OptIn(@ExperimentalWindowFunctions::class) annotation. 
(The latter point is a follow up to what I said before. @OptIn will be more neat on WindowRelationalOperatorFactoryDefault than on DEFAULT_RELATIONAL_OPERATOR_FACTORIES)

2023-01-17 20:12 UTC, vgapeyev reviewed
A couple catch-up comments.

2023-01-17 20:12 UTC, vgapeyev commented on lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/PartiQLCompilerPipelineFactory.kt
> +        val compiler = if (experimentalFeatures) PartiQLCompilerBuilder.experimental() else PartiQLCompilerBuilder.standard()
I expect no annotation will be needed here after `experimental()` method is gone.

2023-01-21 00:18 UTC, yliuuuu commented on lang/src/main/kotlin/org/partiql/annotations/PartiQLExperimental.kt
>  annotation class PartiQLExperimental
Leave it in for now. I don't have a strong opinion on this.

2023-01-21 00:19 UTC, yliuuuu commented on lang/src/test/kotlin/org/partiql/lang/compiler/memorydb/QueryEngine.kt
> +@OptIn(ExperimentalPartiQLCompilerPipeline::class)
I would argue for an internal test class like this, applying annotation for class level makes maintenance a bit easier.

2023-01-21 00:21 UTC, yliuuuu commented on lang/src/main/kotlin/org/partiql/lang/eval/physical/PhysicalBexprToThunkConverter.kt
>      override fun convertWindow(node: PartiqlPhysical.Bexpr.Window): RelationThunkEnv {
I believe this should be an `optin`.

2023-01-24 17:07 UTC, vgapeyev approved these changes
Looks good, but see some follow-up comments.
Also, please update the PR description to reflect the final state.  I hope the informative part of it can make its way into the commit message of the merge.

2023-01-26 00:04 UTC, merged